### ISSUE TITLE
Scrolling When Browser Is Out Of Focus

### ISSUE THREAD

**Issue by chad1008** [tinkertinker/wp-calypso#12]
When another window has focus, scrolling the chat (without clicking so focus remains on the other window) to the end will then scroll the main WordPress.com page being displayed.

If the browser window has focus, scroll behaves normally. The main page isn't scrolled while the cursor is in the chat panel.

Steps to reproduce:
1. open a chat long enough to scroll
2. click into a different window on your desktop
3. hover over the chat panel without clicking and scroll to the top/bottom of the chat
4. keep scrolling

**Comment by andreabadgley** [comment]
Adding that when you keep scrolling at end of chat, the scroll jumps over to the Reader and starts scrolling the Reader. Here's a 35 second video:

https://cloudup.com/c9DeltGNHBm

A couple of extra scrolls are required to get it to jump from the chat sidebar to the Reader. Tested on MacBook Pro trackpad in Firefox.

**Comment by chad1008** [comment]
For completeness, this happened for me in Chrome on a MBP

**Comment by andreabadgley** [comment]
Did some more testing on this on MBP trackpad. Safari and Chrome behave similarly to each other and as reported here: when window is not focused, scrolling will bleed into main body even when hovering over chat sidebar.

In Firefox, the non focused window behaves slightly differently. Firefox requires a couple of extra swipes to jump from chat to main body when bleeding. Also, if you begin scrolling the main body in an unfocused window, the chat will no longer scroll, even when hovering over it, until the main body's scroll reaches the end. I've been trying to upload a 57 second video to Cloudup but it's taking forever to upload. I'll add it here when it's finished.

**Comment by jasmussen** [comment]
Again, very thorough testing, I appreciate this a whole bunch. 

I've tested 5 different techniques for preventing scroll-bleed, and I collected them all here: http://codepen.io/collection/DZOGmL/

As it turns out, in JavaScript, we can't detect where your mouse cursor is, unless the browser window is focused. This seems to be the same behavior in all the major browsers. Since we require JavaScript to do the little scroll-bleed prevention trickery, that means we can't fix this issue. 

Which is annoying, but I don't think it's a deal-breaker. 

I'm glad we explored and tested this, and properly looked for solutions. That way we can point back to this ticket if new issues pop up.
