### ISSUE TITLE
Live chat scrollbleed occurs in Safari on iPad

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#19]
Tested scrolling in live chat component in Safari on iPad. Steps to reproduce:
- Start at URL in Safari on iPad: https://lit-cove-83883.herokuapp.com/
- Log in using WPcom credentials and open chat (someone needs to be logged into HUD)
- Chat enough to create scroll.
- Start scrolling in chat panel on iPad.
- When at the end of chat scroll, scroll jumps to main window and begins scrolling the Reader.

Bleed occurs in both portrait and landscape views.

cc: @jasmussen

**Comment by andreabadgley** [comment]
Scrollbleed also occurs in Firefox browser on iPad. Follow same steps as above, only in Firefox web browser app instead of Safari.

**Comment by andreabadgley** [comment]
Also occurs in Chrome. Same steps as above will result in scrollbleed in Chrome on iPad.

**Comment by jasmussen** [comment]
I tried fixing this today. Seems like there's no easy fix. Let's keep this bug open, should inspiration strike. Here are my findings:
- Applying `preventDefault` does not appear to work properly when attached to `onTouchMove`, so we can't prevent scrolling on a touch device using the same technique we use on desktops. 
- Applying `pointer-events: none;` in CSS to the main `body` element does not work as I thought it would, i.e. it doesn't work either.
- We can easily apply `overflow: hidden;` to `html, body` to prevent all scrolling of the main content, with no page-jog side-effects. The problem here is two-fold. On one hand we want to _only_ apply this on iPads (or iPhones), which requires a fair bit of client detection. On the other hand, we want a reliable way to disable body scrolling when you're scrolling the chat panel. This is particularly challenging since there's no hover event on a touch device. We could theoretically lock scrolling when `ontouchmove` is fired on the panel, but that might bleed into the document below and not work.

It would be nice to prevent scrollbleed to improve the iPad experience, but it's probably okay to postpone this until we have a solid solution to doing so. After all, if you've scrolled up high in the chat backscroll, then "flick" it upwards to get to the end, that's what'll happen, and the flick won't bleed into the underlying content. It will only do that if you keep flicking upwards when at the end.

**Comment by kriskarkoski** [comment]
Moved to https://github.com/Automattic/happychat/issues/187
