### ISSUE TITLE
Open chat when navigating from /me/chat to another screen

### ISSUE THREAD

**Issue by kriskarkoski** [tinkertinker/wp-calypso#29]
Currently, if a user has an active chat at /me/chat and navigates to another part of Calypso, such as Stats, the chat is hidden and must be reopened by clicking "Support Chat" in the sidebar. 

Instead, if a user has an active chat at /me/chat and clicks to another Calypso page we should automatically expand the chat so they don't lose the conversation and need to find that link. This seems especially likely to happen if we're providing Calypso links to them in the chat and they users follows them.

**Comment by andreabadgley** [comment]
Steps to repro from #35:
1. Starting at URL: https://wordpress.com/me/chat
2. Enter a message to start a new chat (no reply from operator yet)
3. Click "Reader" in the masterbar to open https://wordpress.com/
4. The chat window is gone, so click "Support Chat" in the bottom left to reopen the chat window. The initial message in my chat is still there.
5. Click the Gravatar in the masterbar to open https://wordpress.com/me (the chat window is still open on the right)
6. Click "Support Chat" in the sidebar to go back to https://wordpress.com/me/chat
7. The page fully reloads, and a new chat begins (my initial message is gone, and I see the message inviting me to start a new chat)

**Comment by jasmussen** [comment]
I don't know why this occurs to me just now, but I'm thinking this issue should be fixe in a different way.

`/me/chat` was actually created only for the mobile experience. Even though the chatbox is responsive, on mobile there's terrible scroll-bleed which makes the experience almost unusable. As such, when you are on mobile, click the sidebar, click support chat at the bottom, instead of opening a chat panel or dock, you are redirected to the `/me/chat` section. In fact, I believe we intentionally _hid_ the "Support Chat" item on the Me page when we launched this. Can you recall, @beaucollins?

Since then we have also redesigned the sidebar so it can be on all sections. So I propose the following:
1. We hide the "Support Chat" link from the Me section unless you're mobile.
2. We put the new sidebar footer on all sections, so you always have the same, consistent, way of starting a chat. 

I'm going to start work on that.

**Comment by jasmussen** [comment]
Unless anyones scream objections, I will consider this issue fixed when https://github.com/Automattic/wp-calypso/pull/8918 is merged in.

**Comment by kriskarkoski** [comment]
Once Happychat is wired to the contact form we'll still need to check that navigation from /help/contact to Calypso opens the chat panel.

@jasmussen Is there a reason to diverge on the mobile experience or could they go through /help/contact as well since that should have the same full screen chat there once it's hooked up

**Comment by jasmussen** [comment]
We chatted in Slack to clear up any things. 

Here's how it should work on both desktop and mobile, for beta launch:
1. Support chat button is invisible in footer
2. User navigates to /help/contact/ and starts a chat
3. Support chat button becomes visible, until a chat & session is ended
4. All chats are started from /help/contact/

The only place where desktop and mobile diverge, is what happens when they click the support chat button, whenever this button is visible. On desktop this opens a docked sidebar, or panel. On mobile, this redirects you to /me/chat, which is an invisible location that no-one should visit directly.

**Comment by jasmussen** [comment]
Fix merged upstream!
