### ISSUE TITLE
Chat is lost when navigating between Calypso screens on mobile

### ISSUE THREAD

**Issue by rachelmcr** [tinkertinker/wp-calypso#40]
#### Steps to reproduce
1. On a mobile device, starting at URL: https://wordpress.com/
2. Tap "Followed Sites" at the top to open the Reader sidebar
3. Tap "Support Chat" to start a new chat — you are directed to https://wordpress.com/me/chat to start the chat
4. Enter a message and start chatting with an operator
5. Tap on a link in the masterbar to navigate around Calypso — the chat window disappears
6. Find the "Support Chat" link wherever you are and tap it to open chat again
#### What I expected

I expected the chat window to follow me around Calypso (step 5 above), as it does on a desktop browser.

When the chat window disappeared, and I opened chat again (step 6 above) I expected it to reopen my chat where I had left off.
#### What happened instead

The chat window didn't follow me around (step 5 above); I had to hunt for the "Support Chat" link again to reopen it.

And after the chat window disappeared, and I opened chat again (step 6 above), it redirected me back to https://wordpress.com/me/chat, refreshed the screen, and started me over with a brand new chat (no chat history showing from before I navigated away).
#### Browser / OS version

iPhone 6, iOS 9.3.5, Chrome app
#### Context / Source
# manual-testing

**Comment by jasmussen** [comment]
This is a great ticket, and very difficult to "fix" as such. 

The small viewport, combined with the complexity of live chat support (keep in mind a software keyboard will cover half the screen) makes it probably difficult to almost impossible for the live chat box to actually follow the user around the site like it does on a desktop. Even if it was, it would be further complexified by scrollbleed issues, which incidentally caused us to redirect the user to a dedicated support chat page. 

I think it's good for us to offer live chat support via mobile, we should't stop doing that. But I think it's okay for us to apply some artificial limitations on it.

Until https://github.com/Automattic/happychat/issues/8 is implemented, we should show a `confirm` OK/Cancel dialog box when the user navigates away from the chat, informing them that this will end the chat. Something for @beaucollins maybe?

After chat history is implemented, we could rephrase that to suggest the user can come back to the chat after navigating around. We can even consider creating a floating blue tab, olark style, that follows the user around as they navigate away from the chat, but instead of opening a panel with the chat, just links them back to it.

**Comment by kriskarkoski** [comment]
Moved to https://github.com/Automattic/happychat/issues/188
