### ISSUE TITLE
Add ability for user to end chat.

### ISSUE THREAD

**Issue by dwainm** [tinkertinker/wp-calypso#46]
#### What I expected

After completing  a chat.  I'd like to close a chat as user or from the agent's side.
#### What happened instead

The chat goes on endlessly. Closing the chat window doesn't  end the chat.
#### Browser / OS version

Chromes / OSx El Capitan

**Comment by andreabadgley** [comment]
It is currently possible for the agent to end a chat using the `/end` command. When https://github.com/Automattic/happychat/issues/102 is implemented, the user will receive a message that the chat has ended. 

It would be cool for the user to also be able to end the chat.

**Comment by jasmussen** [comment]
Please see also #34 for some context on why this is tricky from a UI point of view.

That aside, I'd appreciate input on how other chat systems, like Olark, provide UI affordances for users to end chats. Is there a permanently visible "end chat" button? Is there an X button that ends the chat, next to a minimize button? Is there a confirm prompt on the X button? Screenshots would be appreciated.

**Comment by andreabadgley** [comment]
We do not currently offer the user the opportunity to close the chat using Olark. This request is definitely an enhancement to consider for the future and is not necessary for beta.

From a user perspective, it's nice to have the option to end the chat and have closure. This also lets the operator know, "This user is finished/resolved" so that the agent can move on without the whole "you hang up first," "No, you hang up first," back and forth of goodbyes.

Here are a couple of ways I've seen other chat/messaging systems do it:
![wp app via helpshift](https://cloud.githubusercontent.com/assets/9036382/18953299/c1b7019c-861b-11e6-95ba-060cf4ef2881.jpg)

![applechat2](https://cloud.githubusercontent.com/assets/9036382/18953187/272916f6-861b-11e6-8d4b-f2f63d13bdb8.jpg)

**Comment by kriskarkoski** [comment]
I agree with the above comments, the concept of ending a chat doesn't _have_ to be user facing (and isn't even available as an option in Olark), but before we launch we will need to think about what user behavior constitutes ending a session and opening an operator up for another chat. 

Currently in Olark I don't think we ever automatically end a chat unless the user leaves WordPress.com. I think there's an open issue where we would give the user a minute or two to return for cases where they left on accident or lost internet briefly, but if the user collapses the chat for X minutes should we automatically /end as well? That's what we need to think about.

I could see there being benefits of having both minimize and close/leave options available to users. The biggest advantage of having a leave option for users is that we wouldn't need to wait for them to go silent or leave for X minutes before considering the chat session over, we could immediately open the operator up for another chat so there might be some small capacity gains with making this user-facing. 

For reference, here's what Olark looks like now:

<img width="320" alt="screen shot 2016-09-29 at 12 10 03 pm" src="https://cloud.githubusercontent.com/assets/1900444/18962184/c825e8f0-863d-11e6-9429-2867ecb10b30.png">

**Comment by jasmussen** [comment]
I like the idea of the user not having to worry about ending a chat, and having that being something "we" take care of. It also fits with the initial vision of Happychat being an ongoing conversation with WordPress.com, that stores all your history.

Since we don't have that history currently though, but we do send chat transcripts, the question remains though, do we want a user facing "button" or other affordance? I'd love to see if we can live without it, and then build it if we find we need it. When that time comes, it could be the new behavior of the close button, where the down arrow would be minimize.

**Comment by andreabadgley** [comment]
> I'd love to see if we can live without it, and then build it if we find we need it. 

We can definitely live without it for now.

**Comment by dwainm** [comment]
+1 for living without it. I also like the idea of having a continuous conversation. The initial thought behind this issue was how familiar I was with the end chat feature all over the web.

**Comment by kriskarkoski** [comment]
We've decided not to add a user-facing end feature for now to go along with our ongoing conversation model. Closing this unless a need surfaces for it in the future.
