### ISSUE TITLE
Support Chat margins inconsistent with Calypso

### ISSUE THREAD

**Issue by rickybanister** [tinkertinker/wp-calypso#49]
#### What I expected

I expected the margin around the chat to have more breathing room at desktop widths—I think the margin is something like 32px at the largest breakpoint. As the window gets smaller the margin should diminish. Similarly, the text input could either have a margin around it or more inner padding at large widths.
#### What happened instead

There are 8px of left/right padding around chat messages regardless of breakpoint. The design works wonderfully at mobile width, but feels too pinned to the corners on larger screens. The reading experience was a little bit tough as a result.

<img width="1451" alt="screen shot 2016-09-07 at 11 33 21 am" src="https://cloud.githubusercontent.com/assets/437258/18318239/f0656d3c-74ee-11e6-8333-928054ac78c8.png">

**Comment by andreabadgley** [comment]
cc @jasmussen

**Comment by jasmussen** [comment]
Excellent feedback. I have addressed this in the Happychat HUD.

I don't know that in the current implementation it makes sense to fix in the frontend client, simply because you're never actually supposed to see such a wide chat panel. That is, your screenshot is showing a bug where the panel is super wide when it's not supposed to be.

I will fix the wide panel in #52, and close this for now.

We have talked about adding a "pop out" button to the panel so you can put the chat in your own window, in such a case it would make a ton of sense to backport the media queries at that time, but that's not quite on the immediate roadmap. Also, if I implement basic media queries with the small panel, it'll invoke simply based on the browser window width, not the panel width, so if we were to have a resizable panel we'd have to do some JS tinkering.
