### ISSUE TITLE
Handle Session ID for closed chat

### ISSUE THREAD

**Issue by mkaz** [tinkertinker/wp-calypso#62]
The current scenario is a session id is created when a chat starts and then while that browser/tab is open will continue using the same session id, even after an operator might of issued an `/end`

An operator resolves an issue and thinks the chat is over, so issues an `/end` which triggers marks the end time in the database and triggers the transcript.

The user might at this point, or maybe a few minutes later, think of a new question and start to chat again, this will add on to the same session_id and once duplicate prevention is in place, a second transcript with the new chat would not go out.

This can be resolved a few ways, laying out some options:
1. Leave as is and let the chat happen on the old session id, the user will not see everything in the transcript e-mail. However, it all still will be recorded and when we get history in place they could see it.
2. Service can create a new session id when a message comes in on an old session, this might happen often for simple "Thanks" or other one word responses and these would need to get `/end` by the operator. Calypso client will need updating to catch the new session id is created response.
3. Catch session end event on calypso and then treat any additional responses as starting a new session creating a session id. Similar to (2) above but handled on client, same issue of one word response sessions.

See: https://github.com/Automattic/happychat/issues/112#issuecomment-254623330

**Comment by mjangda** [comment]
This may be a non-issue once we move to the contact form, but we definitely should start a new session after the user gets the "no operators" message. Right now, the transcript ends up including the "no operators" message if I send a message in the same window later and an operator is around.

/cc @andreabadgley for any thoughts she might have.

**Comment by andreabadgley** [comment]
I agree with Mo that we should definitely start a new session after the "no operators" message so that message isn't included in the transcript, and that that probably will be a non-issue once we move to the contact form. If it does become an issue, maybe that message needs to trigger an `/end` event somehow.

We should not do option 1 above unless we have a way to manually send the second transcript. Sometimes a user might come back after a refund and say "Will I receive an email confirmation of the cancellation?" If we've manually cancelled or refunded in the chat, they will not receive an email, so we often say "This chat is your confirmation." If they don't get the transcript, they don't have a record of that confirmation, which is what they really want: a paper trail.

If we do 2 or 3, am I correct in thinking that the "Thanks" transcript will be suppressed by https://github.com/Automattic/happychat/issues/112#issuecomment-254591419? If so, 2 or 3 sound like the best solution to me. I don't understand the difference between them well enough to give thoughts on one over the other. It sounds like the difference is technical rather than something the HE or user would be affected by.

**Comment by kriskarkoski** [comment]
I like the idea of starting a new session after a user hasn't contacted us for 15 minutes after an /end and otherwise sending a partial duplicate transcript with the old conversation and the new conversation following the /end.
