### ISSUE TITLE
Provide notifications to user in live-chat component

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#7]
When a user receives a new chat message from an operator but is not in the chat (is looking at another window/tab, etc), provide a subtle audible notification or visual notification to browser tab.

**Comment by mjangda** [comment]
Delta has the beginnings of `push-notification` support in Calypso, although, that may not match our specific use case here since we just want local notifications (receive live chat message => show browser notification) and don't need fancy stuff like offline notifications. Plus, browser support for push-api kinda sucks.

Might be able to re-use some stuff though like the auth flow.

**Comment by kriskarkoski** [comment]
We'll also need to make sure a notification is provided user has hidden the chat, but the conversation is still active (this is assuming the user closing the chat doesn't immediately end the conversation).

**Comment by andreabadgley** [comment]
> We'll also need to make sure a notification is provided user has hidden the chat, but the conversation is still active (this is assuming the user closing the chat doesn't immediately end the conversation).

Here's one example for what this could look like. Other mockups [here](https://teamtinker.wordpress.com/2016/03/31/invoking-support-chat/). 

![happychat notification](https://cloud.githubusercontent.com/assets/9036382/17225367/a1c839ca-54d2-11e6-8d3b-8bee3e47a747.png)

**Comment by andreabadgley** [comment]
Can break this into separate issues:
- Floating notifications in Calypso
- Browser sounds
- Little dot
