### ISSUE TITLE
Calypso interface elements clip through chat panel

### ISSUE THREAD

**Issue by mahangu** [tinkertinker/wp-calypso#8]
On several screens in Calypso, interface elements such as buttons and labels currently clip through the chat panel.

_Billing History_ - `/me/billing`
![wl3dlb5zde-2000x2000](https://cloud.githubusercontent.com/assets/10125810/15112998/575a8192-160f-11e6-9f55-a183787caa89.png)

_My Sites > Menus_ - `/menus/`
![screen shot 2016-05-09 at 5 48 30 pm](https://cloud.githubusercontent.com/assets/10125810/15113057/a327e754-160f-11e6-9f06-f9912b052be0.png)

_My Sites > People_ - `/people/team/`
![screen shot 2016-05-09 at 5 48 56 pm](https://cloud.githubusercontent.com/assets/10125810/15113062/b765a210-160f-11e6-8729-7afb1a19676f.png)

Will update this thread with more examples, as and when I find them.

**Comment by mahangu** [comment]
_My Sites > Themes_ - `/design/`

![screen shot 2016-05-09 at 6 01 32 pm](https://cloud.githubusercontent.com/assets/10125810/15113151/29579fae-1610-11e6-97ae-8b16b5e6fbf8.png)

_My Sites > Blog posts / Pages_ - `/posts/` and `/pages`
![screen shot 2016-05-09 at 6 02 48 pm](https://cloud.githubusercontent.com/assets/10125810/15113207/867222f4-1610-11e6-9496-85cf0a23233f.png)

_My Sites > Stats_ - `/stats/insights/`
![screen shot 2016-05-09 at 6 03 11 pm](https://cloud.githubusercontent.com/assets/10125810/15113218/9b3b9378-1610-11e6-8594-783709d1458f.png)

_My Sites > Stats > Days/Weeks/Months/Years_ - `/stats/day|week|month|year`
![screen shot 2016-05-09 at 6 06 09 pm](https://cloud.githubusercontent.com/assets/10125810/15113266/d0ac5254-1610-11e6-9074-3380d92de6f1.png)

_My Sites > Blog posts > Add_ - `/post/`

![screen shot 2016-05-09 at 5 47 58 pm](https://cloud.githubusercontent.com/assets/10125810/15113412/c36b1d04-1611-11e6-8903-049b5513e6d7.png)

**Comment by jasmussen** [comment]
Fixed in the most recent commit to the try/live-chat branch ^^

**Comment by andreabadgley** [comment]
Reopening because the clipping is happening on the Heroku instance as of July 27, 2016. If Heroku isn't running current updates that fix this, feel free to close the issue again :-).

https://lit-cove-83883.herokuapp.com/me/billing
![billing](https://cloud.githubusercontent.com/assets/9036382/17178764/b61c3b90-53e4-11e6-9204-e2a71e677b92.png)

https://lit-cove-83883.herokuapp.com/design
![theme](https://cloud.githubusercontent.com/assets/9036382/17178791/cd5f5774-53e4-11e6-8dae-46695b7834ce.png)
